spring.application.name=api

# ===============================
# Server
# ===============================
server.port=${PORT:8080}

# ===============================
# MySQL datasource
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/dbmechanicalworkshop?useSSL=false&serverTimezone=America/Lima&createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:jose}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jackson.time-zone=America/Lima

# ===============================
# JWT
# ===============================
app.jwt.secret=TallerMecanicoSecretKeyJWT2026SuperSeguraCambiarEnProduccion123456
app.jwt.expiration-ms=86400000

# ===============================
# Error handling
# ===============================
server.error.include-message=always
server.error.include-binding-errors=always